version: '3.8'

services:

  backend:
    container_name: spring-boot-backend
    build:
      context: ./backend
    ports:
      - "8080:8082"
    networks:
      - backend-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
